//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 TaskControl.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDD_TASKCONTROL_FORM            101
#define IDR_MAINFRAME                   128
#define IDR_TASKCOTYPE                  129
#define IDD_SETTINGDLG1                 130
#define IDD_SETTINGDLG2                 131
#define IDD_SETTINGDLG3                 132
#define IDD_SETTINGDLG4                 133
#define IDD_SETTINGDLG5                 134
#define IDD_SETTINGDLG6                 135
#define IDD_JOYSETTINGDLG               136
#define IDD_CHARTDLG                    137
#define IDD_RESULTDLG                   139
#define IDD_SELECTDLG                   142
#define IDD_SELECTVIEW                  143
#define IDD_SETTINGDLG                  145
#define IDD_HARDVIEW                    146
#define IDD_TESTERVIEW                  147
#define IDR_RESULT                      148
#define IDR_MENU1                       149
#define IDD_LISTDLG                     150
#define IDR_MENU2                       151
#define IDD_ANALYSISDLG                 152
#define IDD_DIALOG1                     152
#define IDR_MENU3                       152
#define IDD_PROCESSDLG                  153
#define IDD_SETTINGDLG7                 154
#define IDD_DIALOG2                     155
#define IDD_SETTINGDLG8                 156
#define IDC_OPEN                        1000
#define IDC_LIST1                       1000
#define IDC_SELECT                      1001
#define IDC_LIST2                       1002
#define IDC_TRACK                       1003
#define IDC_MOVEUP                      1003
#define IDC_MOVEDOWN                    1004
#define IDC_MOVEMODE0                   1004
#define IDC_MOVEMODE1                   1005
#define IDC_REVERT                      1006
#define IDC_SETTING                     1007
#define IDC_PAUSE                       1008
#define IDC_START                       1008
#define IDC_PAUSENUM                    1009
#define IDC_VIEWSETTING                 1009
#define IDC_GRADE                       1012
#define IDC_INTERVAL                    1013
#define IDC_ANGLESPEEDMIN               1015
#define IDC_PRACTIME                    1016
#define IDC_ROTATEANGLEMIN              1017
#define IDC_PRACTIME2                   1017
#define IDC_PRACTIME3                   1018
#define IDC_BACKGROUND                  1019
#define IDC_PRACTIME4                   1020
#define IDC_INTER_MIN                   1021
#define IDC_INTER_MAX                   1022
#define IDC_BACKGROUND2                 1023
#define IDC_ACCELERATIONMIN             1024
#define IDC_ACCELERATIONMAX             1025
#define IDC_EXPERTIME                   1026
#define IDC_CODEPAIRMODE0               1027
#define IDC_HOLDTIME1                   1028
#define IDC_ANGLESPEEDMAX               1028
#define IDC_CODEPAIRMODE1               1028
#define IDC_HOLDTIME2                   1029
#define IDC_CODEPAIRNUM                 1029
#define IDC_ROTATEANGLEMAX              1029
#define IDC_HOLDTIME3                   1030
#define IDC_HOLDTIME4                   1031
#define IDC_HOLDTIME5                   1032
#define IDC_HOLDTIME6                   1033
#define IDC_HOLDTIME7                   1034
#define IDC_HOLDTIME8                   1035
#define IDC_SAVE                        1036
#define IDC_HOLDTIME9                   1036
#define IDC_SAVEAS                      1037
#define IDC_HOLDTIME10                  1037
#define IDC_HOLDTIME11                  1038
#define IDC_SAVE2                       1038
#define IDC_HOLDTIME12                  1039
#define IDC_HOLDTIMENUM                 1040
#define IDC_SAVE4                       1040
#define IDC_EVENTMODE0                  1041
#define IDC_EVENTMODE1                  1042
#define IDC_PRACTIMES                   1055
#define IDC_EXPERTIMES                  1056
#define IDC_DISPLAYMODE0                1057
#define IDC_DISPLAYMODE1                1058
#define IDC_SIGNSHOWTIME                1062
#define IDC_TASKNAME                    1063
#define IDC_INCREASEVALUE               1064
#define IDC_MAINTASK0                   1066
#define IDC_MAINTASKMODE0               1066
#define IDC_MAINTASK1                   1067
#define IDC_MAINTASKMODE1               1067
#define IDC_DIRECTION0                  1068
#define IDC_DIRECTION1                  1069
#define IDC_SPEEDMODE0                  1070
#define IDC_SPEEDMODE1                  1071
#define IDC_TOUCHORDER0                 1072
#define IDC_JOY_MOVE_POS                1072
#define IDC_TOUCHORDER1                 1073
#define IDC_JOY_MOVE_NEG                1073
#define IDC_SIGNMEMMODE0                1074
#define IDC_SIGNMEMMODE1                1075
#define IDC_SIGNSHOWMODE0               1076
#define IDC_SIGNSHOWMODE1               1077
#define IDC_SIGNMEMNUM                  1078
#define IDC_MEMTASKMODE0                1079
#define IDC_SIGNMEMTYPE                 1079
#define IDC_MEMTASKMODE1                1080
#define IDC_INITSPEED                   1083
#define IDC_SPEEDMAX                    1084
#define IDC_INITSPEED2                  1084
#define IDC_SPEEDMIN                    1085
#define IDC_SPEED                       1086
#define IDC_PRACMODE                    1087
#define IDC_EXPERMODE                   1088
#define IDC_MAINTASK                    1089
#define IDC_SUBTASK                     1090
#define IDC_PAUSE0                      1091
#define IDC_DISTANCEERROR2              1091
#define IDC_LEFTTOP                     1091
#define IDC_SPEEDMAX2                   1091
#define IDC_PAUSE1                      1092
#define IDC_ANGLEERROR2                 1092
#define IDC_IDC_RIGHTTOP                1092
#define IDC_MAINTASKSTATIC              1093
#define IDC_SUBTASKSTATIC               1094
#define IDC_TASKMODESTATIC              1095
#define IDC_RIGHTBOTTOM                 1095
#define IDC_PRACTIMESSTATIC             1096
#define IDC_SUBTASK2                    1096
#define IDC_EXPERTIMESSTATIC            1097
#define IDC_INITSPEEDSTATIC             1098
#define IDC_SPEEDMAX3                   1098
#define IDC_PRACTIMESTATIC              1099
#define IDC_INITSPEEDSTATIC2            1099
#define IDC_SPEEDMAX4                   1099
#define IDC_EXPERTIMESTATIC             1100
#define IDC_PRACTIMESTATIC2             1100
#define IDC_LEFTBOTTOM                  1101
#define IDC_EXPERTIMESSTATIC2           1101
#define IDC_SPEEDUNITSTATIC             1102
#define IDC_INITSPEEDSTATIC3            1102
#define IDC_SPEEDUNITSTATIC1            1103
#define IDC_SPEEDUNITSTATIC4            1103
#define IDC_INITSPEEDSTATIC4            1103
#define IDC_SPEEDUNITSTATIC2            1104
#define IDC_INITSPEEDUNITSTATIC         1104
#define IDC_SPEEDUNITSTATIC3            1105
#define IDC_SPEEDMAXUNITSTATIC          1105
#define IDC_INITSPEEDUNITSTATIC2        1105
#define IDC_PAUSENUMSTATIC              1106
#define IDC_PRACTIMESTATIC3             1106
#define IDC_SPEEDMAXUNITSTATIC2         1106
#define IDC_PAUSENUMUNIT                1107
#define IDC_PRACTIMESTATIC4             1107
#define IDC_SPEEDSTATIC                 1108
#define IDC_SPEEDMAXSTATIC              1109
#define IDC_ACCELERATIONSTATIC          1110
#define IDC_ACCELERATIONMIDSTATIC       1111
#define IDC_ANGLESPEEDSTATIC            1112
#define IDC_PRACTIMESTATIC5             1112
#define IDC_ANGLESPEEDMIDSTATIC         1113
#define IDC_ROTATESTATIC                1114
#define IDC_CODEPAIRMODESTATIC          1115
#define IDC_ACCELERATIONUNITSTATIC      1115
#define IDC_DISPLAYMODESTATIC           1116
#define IDC_ANGLESPEEDUNITSTATIC        1116
#define IDC_SPEEDMIDSTATIC              1117
#define IDC_ACCELERATIONUNITSTATIC2     1117
#define IDC_HOLDTIMEUNITSTATIC1         1118
#define IDC_SPEEDUNITSTATIC5            1118
#define IDC_SPEEDMIDSTATIC2             1118
#define IDC_HOLDTIMEUNITSTATIC2         1119
#define IDC_SIGNSHOWTIMEUNITSTATIC      1119
#define IDC_ROTATEANGLESTATIC           1119
#define IDC_PRACTIMEUNITSTATIC          1120
#define IDC_EXPERTIMEUNITSTATIC         1121
#define IDC_HOLDTIMEUNITSTATIC5         1122
#define IDC_ROTATEANGLEMIDSTATIC        1122
#define IDC_HOLDTIMEUNITSTATIC6         1123
#define IDC_ROTATEANGLEUNITSTATIC       1123
#define IDC_HOLDTIMEUNITSTATIC7         1124
#define IDC_FREQUENCYUNITSTATIC         1124
#define IDC_EVENTFREQUENCYUNIT          1124
#define IDC_HOLDTIMEUNITSTATIC8         1125
#define IDC_HOLDTIMEUNITSTATIC9         1126
#define IDC_HOLDTIMEUNITSTATIC10        1127
#define IDC_HOLDTIMEUNITSTATIC11        1128
#define IDC_HOLDTIMEUNITSTATIC12        1129
#define IDC_HOLDTIMESTATIC1             1130
#define IDC_HOLDTIMESTATIC2             1131
#define IDC_HOLDTIMESTATIC3             1132
#define IDC_HOLDTIMESTATIC4             1133
#define IDC_HOLDTIMESTATIC5             1134
#define IDC_HOLDTIMESTATIC6             1135
#define IDC_HOLDTIMESTATIC7             1136
#define IDC_HOLDTIMESTATIC8             1137
#define IDC_HOLDTIMESTATIC9             1138
#define IDC_HOLDTIMESTATIC10            1139
#define IDC_HOLDTIMESTATIC11            1140
#define IDC_HOLDTIMESTATIC12            1141
#define IDC_JOYSPEEDMAX                 1142
#define IDC_SPEEDUNITSTATIC6            1142
#define IDC_EXPERTIMEUNITSTATIC3        1142
#define IDC_HOLDTIMEUNITSTATIC13        1142
#define IDC_HOLDTIMEUNITSTATIC3         1142
#define IDC_MSCHART1                    1143
#define IDC_SENSITIVE                   1143
#define IDC_PRACTIMEUNITSTATIC3         1143
#define IDC_HOLDTIMEUNITSTATIC14        1143
#define IDC_HOLDTIMEUNITSTATIC4         1143
#define IDC_FLIENAME                    1144
#define IDC_FILEBROWN                   1145
#define IDC_RESULTLIST                  1146
#define IDC_RESULTLIST2                 1147
#define IDC_CHARTLIST                   1149
#define IDC_PLOT                        1150
#define IDC_TAB1                        1151
#define IDC_ANALYSIS                    1152
#define IDC_DISTANCEERROR               1153
#define IDC_ANGLEERROR                  1154
#define IDC_SIGNMEMTYPESTATIC           1154
#define IDC_CUBENUM1                    1155
#define IDC_PROTOTYPE1                  1156
#define IDC_REFAXIS1                    1157
#define IDC_CUBENUM2                    1158
#define IDC_SAVESETTING                 1158
#define IDC_CUBENUM3                    1159
#define IDC_SAVEASSETTING               1159
#define IDC_APPLICATION                 1159
#define IDC_CUBENUM4                    1160
#define IDC_MAKESURE                    1160
#define IDC_DEFAULT                     1160
#define IDC_PROTOTYPE2                  1161
#define IDC_MAKESURE2                   1161
#define IDC_PROTOTYPE3                  1162
#define IDC_TESTERAGE                   1162
#define IDC_PROTOTYPE4                  1163
#define IDC_TESTERSEX                   1163
#define IDC_MAKESURE3                   1163
#define IDC_REFAXIS2                    1164
#define IDC_TESTERNO                    1164
#define IDC_MAKESURE4                   1164
#define IDC_REFAXIS3                    1165
#define IDC_TESTERNAME                  1165
#define IDC_SESSION                     1166
#define IDC_EVENTFREQUENCY              1168
#define IDC_CUBENUMSTATIC               1169
#define IDC_EVENTFREQUENCY2             1169
#define IDC_PROTOTYPESTATIC             1170
#define IDC_EVENTFREQUENCY3             1170
#define IDC_REFAXISSTATIC               1171
#define IDC_EVENTFREQUENCYSTATIC        1172
#define IDC_CUBENUMSTATIC2              1172
#define IDC_DIRECTIONSTATIC             1173
#define IDC_EVENTFREQUENCYSTATIC2       1173
#define IDC_CUBENUMSTATIC3              1173
#define IDC_INITSPEEDUNIT               1174
#define IDC_CUBENUMSTATIC4              1174
#define IDC_DIRECTIONSTATIC2            1174
#define IDC_HOLDTIMENUMSTATIC           1175
#define IDC_DIRECTIONSTATIC3            1175
#define IDC_EVENTMODESTATIC             1177
#define IDC_PROGRESS1                   1178
#define IDC_OK                          1179
#define IDC_TEXT                        1180
#define IDC_CUSTOM1                     1181
#define IDC_SPEED_CONSTANT              1182
#define IDC_SUBTASK_INTERVAL            1184
#define IDC_PRESENT_TIME                1185
#define IDC_REACT_TIME                  1186
#define IDC_EDIT1                       1186
#define IDC_SMALL_BALL_CLR_R            1187
#define IDC_EDIT2                       1187
#define IDC_SMALL_BALL_CLR_G            1188
#define IDC_BUTTON1                     1188
#define IDC_SMALL_BALL_CLR_B            1189
#define IDC_BKRND_CLR_R                 1190
#define IDC_BKRND_CLR_G                 1191
#define IDC_BKRND_CLR_B                 1192
#define IDC_BALL_CLR_R                  1193
#define IDC_BALL_CLR_G                  1194
#define IDC_BALL_CLR_B                  1195
#define IDC_BALL_SPEED                  1196
#define IDC_BALL_SPEED2                 1196
#define IDC_SPEED2                      1196
#define IDC_BALL_ACC                    1197
#define IDC_BALL_SPEED3                 1197
#define IDC_SPEED3                      1197
#define IDC_BALL_RADIUS                 1198
#define IDC_SMALL_BALL_RADIUS           1199
#define IDC_CHECK_PRAC                  1200
#define IDC_PRAC_TIMES                  1201
#define IDC_CHECK_EXP                   1202
#define IDC_EXP_TIMES                   1203
#define IDC_INTERVAL_TIME               1204
#define IDC_EDIT3                       1205
#define IDC_BALL_CENTER_DIS             1207
#define IDC_BALL_SPEED1                 1210
#define IDC_SPEED1                      1211
#define IDC_FOCUS_TIME                  1212
#define IDC_COUNTDOWN_TIME              1213
#define IDC_PRAC_MODE                   1214
#define IDC_LEFT                        1282
#define IDC_LEFT6                       1282
#define IDC_BOTTOM                      1283
#define IDC_RIGHT                       1284
#define IDC_TOP                         1285
#define IDC_RANDOM                      1286
#define IDC_ACC                         1293
#define ID_JOYSETTING                   32771
#define ID_DISPLAYRESULT                32772
#define ID_TESTER_NEW                   32773
#define ID_TESTER_OPEN                  32774
#define ID_SETTING_OPEN                 32775
#define ID_SETTING_NEW                  32776
#define ID_HARD_ADJUST                  32777
#define ID_HARD_SETTING                 32778
#define ID_RESULT_LIST                  32779
#define ID_ANALYSIS                     32781
#define ID_CHART_DISTANCEERROR          32782
#define ID_CHART_ANGLEERROR             32783
#define ID_CHART_OBJSPEED               32784
#define ID_CHART_POSTSPEED              32785
#define ID_CHART_OBJANGLESPEED          32786
#define ID_CHART_POSTANGLESPEED         32787
#define ID_START                        32790
#define ID_QUIT                         32791
#define ID_TESTER_NOW                   32792
#define ID_SETTING_NOW                  32793
#define ID_BATCH                        32794
#define IDC_SIGNMEMMODESTATIC           65534
#define IDC_SIGNSHOWMODESTATIC          65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1215
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
